//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())")]
    pub name: String,
    pub code: Uuid,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())", nullable)]
    pub description: Option<String>,
    pub in_stock: i64,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())", nullable)]
    pub unit_blip: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
