//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "products", schema_name = "inventory")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub stripe_id: String,
    #[sea_orm(column_type = "Text")]
    pub product_name: String,
    #[sea_orm(column_type = "Text")]
    pub product_code: String,
    pub incoming: i32,
    pub outgoing: i32,
    pub instock: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub product_description: Option<String>,
    pub price: i32,
    pub magma_info: Option<Json>,
}


#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
